## Generate a Vandermonde matrix.

In [47]:
import numpy as np

In [48]:
def vandermatrix(vector,ncols=None,increasing=False):
    if ncols is None:
        ncols = len(vector)
    if increasing:
        mat = np.array([j**i for j in input_vector for i in range(ncols)]).reshape(nrows,ncols)
    else:
        mat = np.array([j**(ncols-1-i) for j in input_vector for i in range(ncols)]).reshape(nrows,ncols)
    return mat

In [49]:
input_vector = np.array([1,2,3,4,5])
vandermatrix(input_vector)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [50]:
vandermatrix(input_vector,4)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [51]:
vandermatrix(input_vector,4,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [52]:
vandermatrix(input_vector,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

## Write a function to find moving average in an array over a window:
## Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [66]:
import numpy as np
arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3

In [67]:
def moving_avg(arr,k):
    lst = []
    for start in range(len(arr)-k+1):
        lst.append(arr[start:start+k].sum()/k)
    return np.array(np.round(lst,2))

In [68]:
print(moving_avg(arr,window))

[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
